from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument("-i", "--input", action="store", dest="inFile", help="Input csv frequencies file generated by CallHap.  ", required=True)
parser.add_argument("-o", "--output", action="store", dest="outFile", help="Output csv for use in further processing.  ", required=True)
o = parser.parse_args()

inputFile = open(o.inFile, 'rb')
outputFile = open(o.outFile, 'wb')
lineNum = 0
for line in inputFile:
    linebins = line.split(',')
    if lineNum == 0:
        outputFile.write("Individual,%s" % ",".join(linebins[:len(linebins)-1]))
    elif lineNum == 1:
        pass
    else:
        numHaps = len(linebins) - 2
        individualCounter = 0
        for lineBinIter in xrange(numHaps):
            for individualIter in xrange(int(float(linebins[lineBinIter+1]))):
                outLine = [0 for x in xrange(numHaps)]
                outLine[lineBinIter] = 1
                outputFile.write("\n%s_%s,%s,%s" % (linebins[0], individualCounter, linebins[0], ",".join([str(x) for x in outLine])))
                individualCounter += 1

    lineNum += 1
inputFile.close()
outputFile.close()